export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT'
export const SET_IMAGE = 'SET_IMAGE'
